event_planner/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views
app_name='main'
urlpatterns = [
    path('', views.index,name='index'),
    path("about/", views.about, name="about"),
    path('services/',views.services,name='services'),
    path('gallery/page=<page>',views.gallery,name='gallery'),
    path('gallery/',views.gallery,name='gallery'),
    path('services/',views.services,name='services'),
    path("contact/", views.contact, name="contact"),
    path("blog/", views.blog, name="blog"),
    path("blog/blogpost/<int:id>", views.blogpost, name="blogpost"),
    path("add-contact-me/",views.contactme, name="contact-me")




]

main/models.py
from django.db import models
from datetime import date
# Create your models here.
class Gallery(models.Model):
    image = models.ImageField(upload_to='gallery/')
    heading = models.CharField(max_length=70)
    time = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.heading

class Blogpost(models.Model):
    post_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50,default="")
    blog_heading = models.CharField(max_length=100, default="")
    blog_description = models.CharField(max_length=5000, default="")
    blogpost = models.TextField(default="")
    pub_date = models.DateField(default =date.today)
    thumbnail = models.ImageField(upload_to='blog/images',default="")
    def __str__(self):
        return self.title
class ContactFormModel(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.CharField(max_length=100)
    contact_number = models.CharField(max_length=20)
    event_detail = models.TextField()

main/views.py
from django.shortcuts import render,redirect
from .models import Gallery,Blogpost, ContactFormModel
from django.core.paginator import Paginator
# Create your views here.
def index(request):
	return render(request,'main/index.html')

def about(request):
	return render(request,'main/about.html')

def contact(request):
	return render(request,'main/contact.html')

def services(request):

	colors=['#0275d8','#5cb85c','#5bc0de','#f0ad4e','#d9534f']
	return render(request,'main/services.html',{'colors':colors})
	colors=['#024f37','#02304f','#7dc1e3','#7de395','#897de3']
	return render(request,'main/services.html',{'colors':colors})

from math import ceil
def gallery(request,page=1):
	posts = Gallery.objects.all().order_by('time').reverse()
	last_page=ceil(len(posts)/20)
	page=int(page)
	if(page<1):
		return redirect('/gallery/')
	if(len(posts)<(page-1)*20):
		#error page
		return redirect('/gallery/')
	else:
		posts=posts[20*(page-1):]
	if(len(posts)>20):
		posts=posts[:20]


	return render(request,'main/gallery.html',{'posts':posts,'last_page':last_page,'page':page,'next_page':page+1,'prev_page':page-1})

def blog(request):
	all_posts = Blogpost.objects.all()
	paginator = Paginator(all_posts, 6)
	page_number = request.GET.get('page')
	myposts = paginator.get_page(page_number)
	print(myposts)
	return render(request,'main/blog.html',
				  {'myposts': myposts})

def blogpost(request, id):
	post = Blogpost.objects.filter(post_id = id)[0]
	print(post)
	return render(request, 'main/blogpost.html',{'post': post})

def handler500(request):
    return render(request, '500.html', status=500)

def contactme(request):
	if request.POST:
		pass
	else:
		return redirect('main:contact')
	first_name  = request.POST.get('firstname')
	last_name  = request.POST.get('lastname')
	email  = request.POST.get('email')
	contact_number = request.POST.get('mobile')
	event_detail  = request.POST.get('eventdetail')

	ContactFormModel.objects.create(first_name=first_name,last_name=last_name,email=email
		,contact_number=contact_number,event_detail=event_detail)
	return redirect('main:contact')

main/templates/main/about.html
{% extends 'main/base.html' %}

{% load static %}
{% block title %}
About Us | Heavenly hitched
{% endblock %}
{% block body %}





{% block head%}
<link rel="stylesheet" type="text/css" href="{% static "main/css/about.css" %}">
<link href="https://fonts.googleapis.com/css2?family=Amaranth&display=swap" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static "main/css/contactmeform.css" %}">

{% endblock %}
<div class="body-container border-padding-less">
<div class="row">

    <div class="col-md-8">
        <div class="center ">
            <h1 class="display-3">About Us</h1>
             <br>
            <p>The foundation of love and a lifelong bond, a wedding is definitely one of the most memorable days of
                life. Here at Heavenly Hitched, we assure you your perfect day. Nothing shorter than a dreamy, finest
                and unforgettable experience. At heavenly hitched, we not only manage a wedding, but we curate it
                thread by thread with love.</p>
            <p>Heavenly Hitched initiated in 2020 by young, enthusiastic, creative and experienced event managers in New
                Delhi. "Dilwalon ki Delhi" as it is fondly called is famous for its big fat Indian weddings, From venue
                selection to theme decor, from authentic food to paradise like outdoors, from tailor made invites to the
                best musical vaganza, we curate everything. We work intimately with the families to give them the best
                memories to cherish.</p>

            <p>Heavenly Hitched delivers highly customized, affordable, and a trendy wedding. We are committed to provide a
                hassle free wedding so that couples and families can focus on the special occasion and only reminisce
                the profound happiness, not the stress. We assure you to make your wedding picture perfect.  We promise to
                value every penny you spend and to design your dream wedding for an unforgettable lifetime experience</p>

        </div>

    </div>

    <div class="col-md-4 center border-padding-1">
        <br><br>
        <h4>Connect with us</h4>
        <!-- Default form register -->
        {% include 'main/contactme_form.html' %}

    </div>
</div>
</div>

{% endblock %}

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title%} {% endblock %}</title>
    <link rel = "icon" href ="{% static "main/images/icon.png" %}"
    type = "image/x-icon">


    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">
    <!--Header font -->
    <link href='https://fonts.googleapis.com/css?family=Emilys Candy' rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="{% static "main/css/base.css" %}">
    {% block head%}
    {% endblock %}
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-light header">
    <div class="container-fluid">
        <button
                class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarTogglerDemo03"
                aria-controls="navbarTogglerDemo03"
                aria-expanded="false"
                aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>

        <a class="navbar-brand" href="{% url 'main:index' %}"><img class="img-fluid" alt="Icon" src="{% static "main/images/icon.png" %}">Heavenly Hitched</a>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:about' %}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:gallery' %}">Gallery</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:services' %}">Services</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:blog' %}">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:contact' %}">Contact Us</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% block body %}
{% endblock %}

<!-- Footer -->
<footer class="page-footer font-small">

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
        <a href="{% url 'main:index' %}"> Heavenlyhitched.com</a>
    </div>
    <!-- Copyright -->

</footer>
<!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/js/mdb.min.js"></script>
</body>
</html>

main/templates/main/blog.html
{% extends 'main/base.html' %}
{% load static %}
}
{% block title %}
Blog | Heavenly hitched
{% endblock %}
{% block head %}
<!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">

<link rel="stylesheet" type="text/css" href="{% static "main/css/blog.css" %}">

{% endblock %}

{% block body %}



<!-- Page Content -->
<div class="container border-padding-1">

    <div class="row my-4">
        {% for item in myposts %}
        <!-- Blog Entries Column -->
        <div class="col-md-6 ">

            <!-- Blog Post -->

            <div class="card mb-4">
                <img class="card-img-top" src="{{item.thumbnail.url}}" alt="Card image cap">
                <div class="card-body">
                    <h2 class="card-title">{{item.blog_heading}}</h2>
                    <p class="card-text">{{item.blog_description}}</p>

                    <a href="blogpost/{{item.post_id}}"
                       class="btn btn-primary stretched-link">Read More</a>
                </div>
                <div class="card-footer text-muted">
                    <p class="blog-post-meta">{{item.pub_date}}
                        <a href="{% url 'main:index' %}">Heavenly Hitched</a></p>
                </div>
            </div>
        </div>

        {% endfor %}


    </div>


    <!-- Pagination -->
    <ul class="pagination justify-content-center mb-4">
        <span class="step-links">
        {% if myposts.has_previous %}
            <a href="?page=1">&larr;</a>
            <a href="?page={{ myposts.previous_page_number }}"> Older</a>
        {% endif %}

        <span class="current">
            Page {{ myposts.number }} of {{ myposts.paginator.num_pages }}.
        </span>

        {% if myposts.has_next %}
            <a href="?page={{ myposts.next_page_number }}">Newer </a>
            <a href="?page={{ myposts.paginator.num_pages }}"> &rarr;</a>
        {% endif %}
    </span>
    </ul>

</div>
<!-- /.container -->

{% endblock %}

main/templates/main/blogpost.html
{% extends 'main/base.html' %}
{% load static %}
}
{% block title %}
BlogPost | Heavenly hitched
{% endblock %}
{% block head %}
<!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<link href="https://fonts.googleapis.com/css2?family=Markazi+Text&display=swap" rel="stylesheet">

<link rel="stylesheet" type="text/css" href="{% static "main/css/blogpost.css" %}">

{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
            <div class="blog-post">
                <h1 class="blog-post-title ">{{post.title}}</h1>

                    <p class="blog-post-meta">{{post.pub_date}}
                        <a href="{% url 'main:index' %}">Heavenly Hitched</a></p>


                <img class="img-fluid rounded" src="{{post.thumbnail.url}}" alt="">
                  
                  <div class="description">
                      {{post.blogpost | safe }}
                  </div>
                  

            </div><!-- /.blog-post -->

    </div><!-- /.row -->
</div>

{% endblock %}

main/templates/main/contact.html
{% extends 'main/base.html' %}

{% block title %}
Contact Us | Heavenly hitched
{% endblock %}
{% block body %}



{% load static %}

{% block head %}
<!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">

<link rel="stylesheet" type="text/css" href="{% static "main/css/contact.css" %}">

{% endblock %}
<script src="{% static "main/javascript/contactmeform.js" %}"></script>
<div class="body-container  ">

<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6 center border-padding ">

        <h1 style="color:white;">Contact Us</h1>
        <!-- Default form register -->
        
        <form  method ="post" onsubmit="return contactmechecker()" action="{% url 'main:contact-me' %}">
          {% csrf_token %}
        <div class="border-padding">


            <input type="text" id="firstname" name="firstname"class="text-input" placeholder="First name">
            <br><br>
            <input type="text" id="lastname" name="lastname" class="text-input" placeholder="Last name">
            <br><br>

            <!-- Phone number -->
            <input type="text" id="mobile" name="mobile" class="text-input" placeholder="Contact Number">
            <br><br>

          <!-- Email -->
          <input type="text" id="email" name="email" class="text-input" placeholder="Email">
            <br><br>

          <textarea class="text-input text-area rounded-0" placeholder="About Event" name="eventdetail" id="eventdetail" rows="5"></textarea>

            <button class="submitbtn" type="submit">Ping us</button>
        </div>
        </form>


</div>
</div>
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6 center social-connect">

    <div>

        <h2 class="center">Let's Connect</h2>
           <div class="border-padding-1">
        <!--Facebook-->
        <a class="btn-floating btn-lg btn-fb" onclick="social_media_facebook()" type="button" role="button"><i class="fab fa-facebook-f"></i></a>
        <!--Instagram-->
        <a class="btn-floating btn-lg btn-ins" onclick="social_media_instagram()" type="button" role="button"><i class="fab fa-instagram"></i></a>
        <!--Youtube-->
        <a class="btn-floating btn-lg btn-yt"  onclick="social_media_youtube()" type="button" role="button"><i class="fab fa-youtube"></i></a>
        <!--WhatsApp-->
        <a class="btn-floating btn-lg btn-whatsapp" onclick="social_media_whatsapp()" type="button" role="button"><i class="fab fa-whatsapp"></i></a>

        <div class="social-desc">
            <div class="social-media-instagram">

            <h5><a href="https://instagram.com/heavenly_hitched?igshid=lpzc3zj8vawu">Click here</a> to checkout our instagram </h5>
        </div>

        <div class="social-media-facebook">
            <h5><a href="https://www.facebook.com/Heavenly-Hitched-101218545034448/">Click here</a> to checkout our facebook</h5>     
        </div>

        <div class="social-media-youtube">
            <h5>Not there yet!</h5>         
        </div>
        
        <div class="social-media-whatsapp">
            <h6>Click to chat !</h6>
            <h5><a href="https://wa.me/917417328972">Mohit </a>- +91 74173 28972 </h5>
            <h5><a href="https://wa.me/918397942336">Himanshu </a>- +91 83979 42336 </h5>
            <h5><a href="https://wa.me/919871245659">Harsh </a>- +91 98712 45659 </h5>
        </div>
        </div>
        
 </div>
    </div>

</div>
    
</div>
     
</div>


<script src="{% static "main/javascript/services.js" %}"></script>
{% endblock %}

main/templates/main/contactme_form.html
{% load static %}
<script src="{% static "main/javascript/contactmeform.js" %}"></script>
<form  method ="post" onsubmit="return contactmechecker()" action="{% url 'main:contact-me' %}">
  {% csrf_token %}
<div class="border-padding">


    <input type="text" id="firstname" name="firstname"class="text-input" placeholder="First name">
    <br><br>
    <input type="text" id="lastname" name="lastname" class="text-input" placeholder="Last name">
    <br><br>

    <!-- Phone number -->
    <input type="text" id="mobile" name="mobile" class="text-input" placeholder="Contact Number">
    <br><br>

  <!-- Email -->
  <input type="text" id="email" name="email" class="text-input" placeholder="Email">
    <br><br>

  <textarea class="text-input text-area rounded-0" placeholder="About Event" name="eventdetail" id="eventdetail" rows="5"></textarea>

    <button class="submitbtn" type="submit">Ping us</button>
</div>
</form>

main/templates/main/gallery.html
{% extends 'main/base.html'%}
{% load static %}
{% block title %} Gallery | Heavenly hitched {% endblock%}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static "main/css/gallery.css" %}">
<script src="{% static "main/javascript/gallery.js" %}"></script>
{% endblock %}

{% block body %}
  {% if page == 1 %}
     <!--slider-->

   <div class="slider" >
       <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <div id="slider-indecator">
          <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
  </ol>
          
        </div>
  

  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="\static\main\images\all\7.jpg"  class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="\static\main\images\all\planner wedding.jpg"  class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="\static\main\images\all\3.jpg"  class="d-block w-100" alt="...">
    </div>
     <div class="carousel-item">
      <img src="\static\main\images\all\1.jpg" class="d-block w-100" alt="...">
    </div>
     <div class="carousel-item">
      <img src="\static\main\images\all\5.jpg" class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>
{% endif %}

     <!--Grid row-->
     <div class="container my-4 ">
    <div class="row ml-1">

      <!--Grid column-->
      {% for post1 in posts %}
 
      <div class="col-md-4 mb-1 col-6 ">
      	<a href="javascript:void(0)" onclick="showMyImage({{post1.id }});"><img src="{{post1.image.url }}" class="img-fluid mb-4" alt="" id="{{post1.id }}"
          data-wow-delay="0.1s"></a>
      </div>
      
      {% endfor %}

    </div>
    <div id="image-popup" class="image-popup" onclick="hide_popup()">

  <!-- The Close Button -->

 
  <!-- Modal Content (The Image) -->
  <img class="image-in-popup" id="image-in-popup">

  <!-- Modal Caption (Image Text) -->
  <div id="caption"></div>
</div>

<nav class="center" aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <li class="page-item">
    	{% if page == 1 %}
      <a class="page-link" href="javascript:void(0)" style="color:gray;" aria-label="Previous">
        <h2><span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span></h2>
      </a>
      {% else %}
      <a class="page-link" href="{% url 'main:gallery' page=prev_page %}" aria-label="Previous">
        <h2><span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span></h2>
      </a>
      {% endif %}
    </li>
    <li class="page-item ml-4">
    	{% if page == last_page %}
      <a class="page-link" href="javascript:void(0)" style="color:gray;" aria-label="Next">
        <h2><span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span></h2>
      </a>
      {% else %}
      <a class="page-link" href="{% url 'main:gallery' page=next_page %}" aria-label="Next">
        <h2><span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span></h2>
      </a>
      {% endif %}
    </li>
    </form>
    
  </ul>
</nav>

  </div>


{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html'%}
{% load static %}
{% block title%}Heavenly Hitched {% endblock %}

{% block head%}
<link rel="stylesheet" type="text/css" href="{% static "main/css/index.css" %}">
<link href="https://fonts.googleapis.com/css2?family=Bree+Serif&family=Mincho&display=swap" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static "main/css/contactmeform.css" %}">
{% endblock %}


{% block body%}
<div class="message-container">
	<img class="message-background-img"src="{% static "main/images/home/message-background.jpg" %}"  alt=" background for theme message" style="width:100%;">

	<div class="message-block">
		<h3>You Dream it, We Take Care Of It</h3><hr>
		<p style="float:right;">~Heavenly hitched</p>

	</div>
</div>​
<div class="message-block-small">
	<h5>You Dream it, We Take Care Of It</h5><hr>
	<p >~Heavenly hitched</p>

</div>
    <div class="body-container border-padding-less">
	<div class="what-we-do">
		<div class="center"><h2>What We Do</h2></div>
		<div class="row ">
			<div class="col-sm-4 ">
				<h5>Venue booking</h5>
				<p>We offer you most supreme and affordable locations in Delhi-NCR.</p>
			</div>
			<div class="col-sm-4">
				<h5>Hospitality & Logistics</h5>
				<p>Wedding is probably the most significant day of anyone’s life. But also the talk of the town . Heavenly Hitched promises the most comfortable and hustle free wedding so, you will be the most admired host.
				</p>
			</div>
			<div class="col-sm-4">
				<h5>Decor & Styling</h5>
				<p>Decoration is one of the crucial factor of wedding. Here we are to give you the most trendy themes, the picturesque venue and also the cost-effective stylings.</p>
			</div>

		</div>

		<div class="row ">
			<div class="col-sm-4">
				<h5>Gifting</h5>
				<p>Any amount of gratitude is not enough for those who blessed you on your wedding. Some personalized gifts and goodies would be sweetest gesture and a token of love and respect. We respect your sentiments and assure you to ace the giftings.</p>
			</div>
			<div class="col-sm-4">
				<h5>Photo & Videography</h5>
				<p>Photos and videos are here to cherish forever. We have professional team mates , who have firm hands in videography and photography. So be ready for the cinematic pre-wedding shoot and perfect pictures of every special moment.</p>
			</div>
			<div class="col-sm-4">
				<h5>Hair & Makeup</h5>
				<p>A bride is the most excited person when it comes to look. Wait! Why only bride? The groom has to be look flawless. Heavenly Hitched helps you to look nothing more than perfect on your D-day.</p>
			</div>

		</div>
	</div>

	<div class="row border-padding">
		<div class="col-sm-4 py-3 ">
			<a href="{% url 'main:services' %}">
				<img src="{% static "main/images/home/services-background.jpg" %}" class="center-image" alt="background for theme message" >
				<div class="thumb-caption">Services</div>

			</a>
		</div>

		<div class="col-sm-4 py-3 ">
			<a href="{% url 'main:gallery' %}">
				<img src="{% static "main/images/home/gallery-background.jpg" %}" class="center-image"alt="background for theme message" >
				<div class="thumb-caption">Gallery</div>
			</a>

		</div>

		<div class="col-sm-4 py-3 ">
			<a style="padding-right:0px;"href="{% url 'main:about' %}">
				<img src="{% static "main/images/home/about-background.jpg" %}" class="center-image"alt="background for theme message" >
				<div class="thumb-caption">About</div>
			</a>

		</div>
	</div>

	<div class="why-us center">

		<h1>Why us?</h1><hr>
		<div class="border-padding-less">
			<h3>Why choose us as your Destination wedding planner?</h3>

			<p>Even small decisions can add up to big savings when you have a planner what they are doing. Here we assure you to make the most of your wedding budget. We help to coordinate right from the engagement to reception. You just need to cherish each and every moment of your wedding. We are here to make your wedding a piece of cake for you. We are there to manage the conversations between you and the venue, negotiating rates for things like catering and confirming the timeline to ensure everything goes smoothly
			</p>

		</div>

		<div class="border-padding-less">
			<h3>Decor and Venue Bookings</h3>

			<p>Wedding decoration is one of the most considered attractions of one’s D-day. The right decoration adds life to the surrounding. Heavenly hitched promise you the drooling venues and decors which make everyone stop and stare. Right from the welcome board to tables of the celebrants and to the aisle runner, everything that matches your wedding fantasies. We are furnishing nearly every decor style the contemporary, minimalist and traditional. We persuade the trendiest weddings in the town in Delhi-NCR.

			</p>
		</div>


		<hr>
	</div>

	<div class="row">

		<div class="col-md-6">
			<div class="center border-padding-less">
				<br>
				<h1>How We Work</h1>

				<p class="border-padding">  As your wedding companion we, lay hold on every  responsibilities from drafting timeline and working with bride and groom to their attires , every ceremony, venues, guests , music, dance and food. We are full service planners, we specially eyed your budget and turn magic into reality.
				</p>
				<p>We are here to handle the shopping , so you will have a stress free day. We will provide the best photographers of the town for those perfect shots of your wedding which you can cherish live long. We guarantee you the “oh so delicious food”, and the most picturesque vendors. And yes, we owned the entertainment section also.
				</p>
			</div>
		</div>


		<div class="col-md-6 center border-padding-1">
			<div>
				<br>
				<h3>Request a call? Just fill this out</h3>
				<!-- Default form register -->
				{% include 'main/contactme_form.html' %}
			</div>


		</div>

	</div>
</div>


	{% endblock %}